// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDeBloco_FimDeSemana.Data;

#nullable disable

namespace ProjetoDeBloco_FimDeSemana.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Cardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .IsUnique();

                    b.ToTable("Cardapios");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.CardapioPersonalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardapioDisponivelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardapioDisponivelId");

                    b.HasIndex("EventoId");

                    b.ToTable("CardapiosPersonalizados");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDoEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GerenciaReservaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HorarioDeFuncionamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GerenciaReservaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.GerenciaReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.ItemCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardapioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CardapioId");

                    b.ToTable("ItensDoCardapio");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Pagamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeDeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Cardapio", b =>
                {
                    b.HasOne("ProjetoDeBloco_FimDeSemana.Models.Evento", "Evento")
                        .WithOne("Cardapio")
                        .HasForeignKey("ProjetoDeBloco_FimDeSemana.Models.Cardapio", "EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.CardapioPersonalizado", b =>
                {
                    b.HasOne("ProjetoDeBloco_FimDeSemana.Models.Cardapio", "CardapioDisponivel")
                        .WithMany()
                        .HasForeignKey("CardapioDisponivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoDeBloco_FimDeSemana.Models.Evento", "Evento")
                        .WithMany("CardapiosPersonalizados")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardapioDisponivel");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Evento", b =>
                {
                    b.HasOne("ProjetoDeBloco_FimDeSemana.Models.GerenciaReserva", "GerenciaReserva")
                        .WithMany("Eventos")
                        .HasForeignKey("GerenciaReservaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoDeBloco_FimDeSemana.Models.Usuario", "Usuario")
                        .WithMany("Eventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GerenciaReserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.GerenciaReserva", b =>
                {
                    b.HasOne("ProjetoDeBloco_FimDeSemana.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.ItemCardapio", b =>
                {
                    b.HasOne("ProjetoDeBloco_FimDeSemana.Models.Cardapio", "Cardapio")
                        .WithMany("ItensDoCardapio")
                        .HasForeignKey("CardapioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cardapio");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Usuario", b =>
                {
                    b.HasOne("ProjetoDeBloco_FimDeSemana.Models.Pagamentos", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Cardapio", b =>
                {
                    b.Navigation("ItensDoCardapio");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Evento", b =>
                {
                    b.Navigation("Cardapio");

                    b.Navigation("CardapiosPersonalizados");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.GerenciaReserva", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("ProjetoDeBloco_FimDeSemana.Models.Usuario", b =>
                {
                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
